# Generated by Django 3.2.9 on 2021-11-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedapp', '0003_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.CharField(max_length=280),
        ),
    ]
